### ISSUE TITLE
Allow custom mapping from FieldName to Environment Variable Name

### ISSUE THREAD

**Issue by niondir** [caarlos0/env#319]
```
type Config struct {
	Test1   string
	TestJson string `json:"TestJson"`
}
```

With the above struct, I like to customized the following two things:
- When setting `TagName: "json"` I want to get "TEST_JSON" as env variable name instead of "TestJson"
- When setting `UseFieldNameByDefault=true` I like to customize that "Test1" will end up in TEST_1 instead of TEST1

Instead of change the default or adding multiple options, maybe the best solution would be to allow setting a mapping method that gets from the `fieldParams.Key` to the environment variable name.

**Comment by caarlos0** [comment]
`TagName` is meant to allow to more easily migrate from other env libraries, not to share with `json` or anything else. 

`UseFieldNameByDefault` compounds the field name only if there is no `env:` tag (or whatever was set with `TagName`) set.

None of these handle what you want to do.
I think its best to use `env:"THE_KEY_YOU_WANT"` instead of adding more options.

On a side note, if you name your field `TestJSON` and set `UseFieldNameByDefault` it should result in `TEST_JSON`.
